In [1]:
# 1. Импорт библиотеки NumPy
import numpy as np

# 2. Примеры создания массивов с хаотичными числами (не в последовательном порядке)

# 2.1 Создание массива из обычного списка с хаотичными числами
chaotic_list = [42, 17, 93, 5, 78, 23, 56, 89, 11, 34]
array_from_chaotic_list = np.array(chaotic_list)
print("1. Массив из хаотичного списка (не по порядку):")
print(array_from_chaotic_list)
print()

# 2.2 Создание двумерного массива с хаотичными числами
chaotic_matrix_data = [
    [15, 87, 3, 42],
    [99, 21, 66, 8],
    [74, 32, 50, 91]
]
chaotic_matrix = np.array(chaotic_matrix_data)
print("2. Двумерный массив с хаотичными числами:")
print(chaotic_matrix)
print()

# 2.3 Создание массива с использованием arange и последующее "перемешивание"
ordered_array = np.arange(20)  # Сначала создаем упорядоченный массив 0-19
print("3.1 Упорядоченный массив от 0 до 19:")
print(ordered_array)

# Перемешиваем массив, чтобы сделать его хаотичным
np.random.shuffle(ordered_array)
print("3.2 Тот же массив после перемешивания (хаотичный порядок):")
print(ordered_array)
print()

# 2.4 Создание массива из специально подобранных хаотичных чисел
custom_chaotic = np.array([100, 7, 45, 82, 19, 63, 28, 94, 51, 76, 3, 88])
print("4. Специально подобранный хаотичный массив:")
print(custom_chaotic)
print()

# 2.5 Создание многомерного массива с хаотичными числами
multi_dim_chaotic = np.array([
    [[5, 27, 13], [48, 2, 39]],
    [[71, 34, 60], [19, 84, 6]],
    [[92, 45, 78], [31, 67, 23]]
])
print("5. Трехмерный массив с хаотичными числами (форма 3x2x3):")
print(multi_dim_chaotic)
print(f"   Форма массива: {multi_dim_chaotic.shape}")
print()

# 3. Демонстрация атрибутов массива
print("6. Демонстрация атрибутов для chaotic_matrix:")
print(f"   Форма массива (shape): {chaotic_matrix.shape}")
print(f"   Тип данных (dtype): {chaotic_matrix.dtype}")
print(f"   Размерность (ndim): {chaotic_matrix.ndim}")
print(f"   Общее количество элементов (size): {chaotic_matrix.size}")
print()

# 4. Примеры индексирования и срезов

# 4.1 Получение отдельных элементов из хаотичного массива
print("7. Индексирование хаотичного массива:")
print(f"   chaotic_matrix[0, 1] = {chaotic_matrix[0, 1]}")  # 87
print(f"   chaotic_matrix[2, 3] = {chaotic_matrix[2, 3]}")  # 91
print(f"   custom_chaotic[5] = {custom_chaotic[5]}")        # 63
print()

# 4.2 Извлечение подмассивов из хаотичных данных
print("8. Извлечение подмассивов:")

# Получаем вторую строку из хаотичной матрицы
second_row = chaotic_matrix[1, :]
print(f"   Вторая строка chaotic_matrix: {second_row}")

# Получаем элементы с индексами 2, 5, 8 из custom_chaotic
selected_indices = custom_chaotic[[2, 5, 8]]
print(f"   Элементы с индексами 2, 5, 8 из custom_chaotic: {selected_indices}")

# Срез с шагом: каждый третий элемент
every_third = custom_chaotic[::3]
print(f"   Каждый третий элемент из custom_chaotic: {every_third}")
print()

# 5. Примеры векторных операций и базовых статистик

# 5.1 Создадим два хаотичных массива для операций
chaotic_array_a = np.array([17, 42, 8, 95, 23, 71, 56, 33])
chaotic_array_b = np.array([5, 88, 29, 64, 12, 47, 91, 20])

print("9. Векторные операции с хаотичными массивами:")

# 5.2 Поэлементное сложение
sum_result = chaotic_array_a + chaotic_array_b
print(f"   Сложение: {chaotic_array_a} + {chaotic_array_b} = {sum_result}")

# 5.3 Поэлементное умножение
mult_result = chaotic_array_a * chaotic_array_b
print(f"   Умножение: {chaotic_array_a} * {chaotic_array_b} = {mult_result}")

# 5.4 Поэлементное вычитание
sub_result = chaotic_array_a - chaotic_array_b
print(f"   Вычитание: {chaotic_array_a} - {chaotic_array_b} = {sub_result}")
print()

# 5.5 Базовые статистические операции
print("10. Статистика для хаотичного массива chaotic_array_a:")
print(f"   Исходный массив: {chaotic_array_a}")

mean_value = np.mean(chaotic_array_a)
print(f"   Среднее значение: {mean_value:.2f}")

median_value = np.median(chaotic_array_a)
print(f"   Медиана: {median_value}")

std_value = np.std(chaotic_array_a)
print(f"   Стандартное отклонение: {std_value:.2f}")

min_value = np.min(chaotic_array_a)
max_value = np.max(chaotic_array_a)
range_value = max_value - min_value
print(f"   Минимальное: {min_value}, Максимальное: {max_value}, Размах: {range_value}")

# 5.6 Сортировка хаотичного массива
print("\n11. Сортировка хаотичного массива:")
print(f"   До сортировки: {custom_chaotic}")
sorted_array = np.sort(custom_chaotic)
print(f"   После сортировки: {sorted_array}")

# 5.7 Поиск уникальных элементов в хаотичном массиве
array_with_duplicates = np.array([17, 42, 8, 42, 23, 17, 56, 8])
print(f"\n12. Поиск уникальных элементов в массиве с повторениями:")
print(f"   Исходный: {array_with_duplicates}")
unique_elements = np.unique(array_with_duplicates)
print(f"   Уникальные: {unique_elements}")

1. Массив из хаотичного списка (не по порядку):
[42 17 93  5 78 23 56 89 11 34]

2. Двумерный массив с хаотичными числами:
[[15 87  3 42]
 [99 21 66  8]
 [74 32 50 91]]

3.1 Упорядоченный массив от 0 до 19:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
3.2 Тот же массив после перемешивания (хаотичный порядок):
[ 6 17  5  9  3 15  4 16 13  8 19  7  2 14 18  1  0 11 12 10]

4. Специально подобранный хаотичный массив:
[100   7  45  82  19  63  28  94  51  76   3  88]

5. Трехмерный массив с хаотичными числами (форма 3x2x3):
[[[ 5 27 13]
  [48  2 39]]

 [[71 34 60]
  [19 84  6]]

 [[92 45 78]
  [31 67 23]]]
   Форма массива: (3, 2, 3)

6. Демонстрация атрибутов для chaotic_matrix:
   Форма массива (shape): (3, 4)
   Тип данных (dtype): int64
   Размерность (ndim): 2
   Общее количество элементов (size): 12

7. Индексирование хаотичного массива:
   chaotic_matrix[0, 1] = 87
   chaotic_matrix[2, 3] = 91
   custom_chaotic[5] = 63

8. Извлечение подмассивов:
   Вторая строка ch